/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JackButton {
        /**
          * Button Style
         */
        "appearance": string;
        /**
          * Is it a link?
         */
        "link": string;
        /**
          * Is the link external?
         */
        "outside": boolean;
    }
    interface JackCard {
        /**
          * Card content
         */
        "content": string;
        /**
          * Card title
         */
        "heading": string;
    }
}
declare global {
    interface HTMLJackButtonElement extends Components.JackButton, HTMLStencilElement {
    }
    var HTMLJackButtonElement: {
        prototype: HTMLJackButtonElement;
        new (): HTMLJackButtonElement;
    };
    interface HTMLJackCardElement extends Components.JackCard, HTMLStencilElement {
    }
    var HTMLJackCardElement: {
        prototype: HTMLJackCardElement;
        new (): HTMLJackCardElement;
    };
    interface HTMLElementTagNameMap {
        "jack-button": HTMLJackButtonElement;
        "jack-card": HTMLJackCardElement;
    }
}
declare namespace LocalJSX {
    interface JackButton {
        /**
          * Button Style
         */
        "appearance"?: string;
        /**
          * Is it a link?
         */
        "link"?: string;
        /**
          * Is the link external?
         */
        "outside"?: boolean;
    }
    interface JackCard {
        /**
          * Card content
         */
        "content"?: string;
        /**
          * Card title
         */
        "heading"?: string;
    }
    interface IntrinsicElements {
        "jack-button": JackButton;
        "jack-card": JackCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jack-button": LocalJSX.JackButton & JSXBase.HTMLAttributes<HTMLJackButtonElement>;
            "jack-card": LocalJSX.JackCard & JSXBase.HTMLAttributes<HTMLJackCardElement>;
        }
    }
}
